CREATE TABLE generation_task (
    id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
    appId bigint NOT NULL COMMENT '应用 ID',
    userId bigint NOT NULL COMMENT '用户 ID',
    attachmentId bigint NULL COMMENT '本次生成使用的附件 ID',
    taskType varchar(32) NOT NULL DEFAULT 'generate' COMMENT '任务类型：generate/build/deploy/repair',
    status varchar(32) NOT NULL DEFAULT 'pending' COMMENT 'pending/running/success/failed/canceled',
    currentStep varchar(64) NULL COMMENT '当前步骤',
    inputPrompt text NOT NULL COMMENT '用户原始输入',
    modelPrompt mediumtext NOT NULL COMMENT '实际发送给模型的 prompt',
    codeGenType varchar(64) NOT NULL COMMENT '代码生成类型',
    errorMessage text NULL COMMENT '失败原因',
    tokenUsage bigint NOT NULL DEFAULT 0 COMMENT 'token 消耗',
    toolCallCount int NOT NULL DEFAULT 0 COMMENT '工具调用次数',
    startTime datetime NULL COMMENT '开始时间',
    endTime datetime NULL COMMENT '结束时间',
    createTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDelete tinyint NOT NULL DEFAULT 0,
    INDEX idx_appId (appId),
    INDEX idx_userId (userId),
    INDEX idx_status (status),
    INDEX idx_appId_createTime (appId, createTime),
    INDEX idx_userId_createTime (userId, createTime)
);
