CREATE TABLE IF NOT EXISTS tool_call_record (
    id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
    taskId bigint NULL COMMENT '生成任务 ID',
    appId bigint NOT NULL COMMENT '应用 ID',
    userId bigint NULL COMMENT '用户 ID',
    toolName varchar(128) NOT NULL COMMENT '工具名称',
    displayName varchar(128) NOT NULL COMMENT '工具展示名',
    toolCategory varchar(64) NOT NULL COMMENT '工具类别：file/build/deploy/knowledge/control',
    riskLevel varchar(32) NOT NULL COMMENT '风险等级：low/medium/high',
    callSource varchar(64) NULL COMMENT '调用来源：generate/repair/manual',
    status varchar(32) NOT NULL COMMENT 'success/failed/rejected',
    argumentsJson mediumtext NULL COMMENT '脱敏后的调用参数',
    resultSummary mediumtext NULL COMMENT '执行结果摘要',
    errorMessage varchar(2048) NULL COMMENT '错误信息',
    durationMs bigint NOT NULL DEFAULT 0 COMMENT '耗时',
    createTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDelete tinyint NOT NULL DEFAULT 0,
    INDEX idx_taskId (taskId),
    INDEX idx_appId (appId),
    INDEX idx_toolName (toolName),
    INDEX idx_status (status),
    INDEX idx_createTime (createTime)
);
